@startsalt
{
{+
  Введення бюджету та часу
  ----------------------------------
  Тип плану:
  ^Тижневий^^ 

  Бюджет:
  [ 500 грн ]

  Кількість прийомів їжі:
  ^2^^ 

  [Назад] | [Далі ➜]
}
}
@endsalt
