@startsalt
{
{+
  Введення параметрів харчування
  ---
  Калорійність: 
  [ 2000 ккал ]
  Ціль: 
  ^Схуднення^^
  ---
  Обмеження:
  [ ] Без глютену
  [x] Без лактози
  [ ] Веган
  ---
  Алергії: 
  [ Горіхи, мед ]
  ---
  [Далі ➜]
}
}
@endsalt
