@startsalt
{
{+
  Перегляд доступних рецептів
  ---
  "Салат Цезар"           | "350 ккал"  | "80 грн"
  "Вівсянка з фруктами"   | "280 ккал"  | "40 грн"
  "Котлета з гречкою"     | "500 ккал"  | "90 грн"
  ---
  [ ] Додати до плану
  [Назад] | [Далі ➜]
}
}
@endsalt
